sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: Ok5qWeyqVUcE9oPH/poB1Sx+ZQ6XuflwpgVMvoaZmCKkwA/jwB+i788DGRKVpDCZuXUTzDxy/obg2dXWYtLpuNCWWQa3n7Ng7sEYHiweFKb9C4p704C6MSuzaas3rchsXjDUR8X+3uLMBRYpvRWVz4l+2qYPQPrNLSRkdgL5/ZbTMKYoJkUeOEVERTNDEkcB3+OQ4UNqWP18/LFj0ACisee6fyuky49oyYxYfzR6l0Y0tp/zA5pmPh5jb9lbAZabknYMB65FbWO/lOwBx9UWzUtUNM252K8MaTG5fsmgbqcDbCkmBtCD2q8/m1Eys6DBVcCUPhHQfcM3uOIfeeSw+d/UTTFLPCsduMliP5M8MIWArlLLbj0uBAdylK1bviflF1jKEMSx8h88/hADdfwlahSgz5rgLMIm26iw02WyQ9/ruRKdrbOKODsmTVDX9BIiqURBpMp6qktROYYTh9XKyvIlLxPwGKHpuL6oCw/BctW8OItnrbvKitDXEazCaTcbXeK1y+xKbR6Thu3FbGF20gcXskDETruOA5cPL0pfb+BszLAg7HAHjUaSSFevlcE0PdX+96PpTBC0Reg5FPxLimVhdyNuKbEf2snODp0abLA2kFQ4CbkbL6KvgDajLwg75bwLkZQoRleXTx9GAMSmYpMcM6fAXNu7L41A+FQNRDs=}, {secure: na/9jCdVHCNO4sQ3rWe6lQKz3wrDZ+sJWccT3QQ0D4c9qTahs48lho1ixe2Hruu2pmnX+v5RJb2xZj+VWwTCkV7GZ0iHmWctRTgeHPMnJXoWeDCnrUKuvoHG3JyfeXP0yNU6AivnyhyrT1bwqIzD2cc/WfapP/kk4Jg8OieJa2TZmzXi5kzEhG8ScwuPWMaBtEwYUtBLP9bl/hhjm/2wAWh4uSPK8yPTg1ev0QdrNh+5S5fND/uarnfDCvzf0NXb5yIkoShw1/uhSyLoGVqld+fgnabuYfKle9LsEp4IHo7AIoy8fL0TOUFhxpxmyMT2UV7R5EGCTyF8rOgEKuc7OsjEwHw30KIpLcJ8UjR1KYF4+eKTAKBAKUko5AarL0Ef5t5gDragx6/PRK2b3u2PAKnfZMIyG110Y/niWUw2XmSe+RjrLiZYGxTs+75IJh+i6uMC+B7imSA4ISLYdn15QjbpGu/cNZeNvR25uEMFX5mXk7hkJDUZ0sKE6XmVfjLzDZ1FWsO9OtDqzJxgExiNzSEa8S4cy7LDD3i16W7//IbkswKK5mSalfgQxuGftvzZ+vNWmrtJVjdiOAEN32B21tLefW56OOoN42s7VavwsjuaweHNC+KpuSD+w2bV38D2czFyc2RgCrY10N7gwy+7X3NYEIvTT9KZ4d7ts5EN3rE=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
